[1]
type=":Chain"
[1.kwargs]

[1.1]
type=":Dense"
args = [1, 10, ":relu"]
[1.1.kwargs]
":bias" = true
":init" = ":(Flux.glorot_uniform)"

[1.2]
type=":Dense"
args = [10, 3, ":tanh"]
[1.2.kwargs]
":bias" = true
":init" = ":(Flux.glorot_uniform)"

[1.3]
type = "generic"
args = ["x -> x .+ 1.0"]
[1.3.kwargs]
